# Generated by Django 4.0.3 on 2022-03-30 15:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_car_photo_order_status_order_user_profilis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Aprašymas'),
        ),
    ]
